# Generated by Django 2.0.6 on 2018-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(default='www.google.com', max_length=250),
            preserve_default=False,
        ),
    ]
