# Generated by Django 2.0.6 on 2018-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('images', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
